detect: 
	python3 detect.py --source 0 --weights scripts/yolor_p6.pt --conf 0.25 --img-size 1280 --device 0

node:
	python3 node.py --source 0 --weights scripts/yolor_p6.pt --conf 0.25 --img-size 1280 --device 0